#ifndef MISSION_H
#define MISSION_H

#include "defines.h"
#include "game_enums.h"
#include "str.h"

//TODO: this should kinda just be autogenerated, as a giant list

// Enemy arrays for each level
Character_Name sandbox_enemies[] = {
    Character_Name_Red_Jester,
    Character_Name_Clown,
    Character_Name_Puppet,
    Character_Name_Doll
};

Character_Name worshipper_enemies[] = {
    Character_Name_Worshipper,
};


Game_Level_Data get_level_data(const Level_Name level_name)
{
    switch (level_name)
    {
    case Level_Name_None:
        break;
    case Level_Name_Sandbox:
        return (Game_Level_Data){
            .mission_name = Level_Name_Sandbox,
            .mission_to_unlock = Level_Name_None,
            .Display_Name = STRING("SANDBOX"),
            .enemy_count = ARRAY_SIZE(sandbox_enemies),
            .enemy_units = sandbox_enemies,
            .starting_turn_initiative = Turn_Initiative_Player,
            .is_debug_level = true,
            .ready_for_playtest = false,
        };
        break;
    case Level_Name_Tutorial:
        break;
    case Level_Name_Worshipper:
        return (Game_Level_Data){
            .mission_name = Level_Name_Worshipper,
            .mission_to_unlock = Level_Name_BurningSoul,
            .Display_Name = STRING("Worshipper"),
            .enemy_units = worshipper_enemies,
            .enemy_count = ARRAY_SIZE(worshipper_enemies),
            .starting_turn_initiative = Turn_Initiative_Player,
            .is_debug_level = false,
            .ready_for_playtest = false,
        };
        break;
    case Level_Name_BurningSoul:
        break;
    case Level_Name_IceQueen:
        break;
    case Level_Name_SunMoonTwin:
        break;
    case Level_Name_BrotherInArms:
        break;
    case Level_Name_BloodBrothers:
        break;
    case Level_Name_HealSquad:
        break;
    case Level_Name_Freezer:
        break;
    case Level_Name_MetalStar:
        break;
    case Level_Name_Abyssal:
        break;
    case Level_Name_Slimes:
        break;
    case Level_Name_CountDown:
        break;
    case Level_Name_ReversalReversal:
        break;
    case Level_Name_Angel:
        break;
    case Level_Name_Demon:
        break;
    case Level_Name_FusionMania:
        break;
    case Level_Name_Persona:
        break;
    case Level_Name_DisfiguredMass:
        break;
    case Level_Name_InsanityProgenitor:
        break;
    case Level_Name_Dancer:
        break;
    case Level_Name_Player:
        break;
    case Level_Name_Law:
        break;
    case Level_Name_Shield:
        break;
    case Level_Name_Time1:
        break;
    case Level_Name_Time2:
        break;
    case Level_Name_Time3:
        break;
    case Level_Name_Time4:
        break;
    case Level_Name_Time5:
        break;
    case Level_Name_Tribe:
        break;
    case Level_Name_Conjure:
        break;
    case Level_Name_3SisterFather:
        break;
    case Level_Name_MultiElemental:
        break;
    case Level_Name_MPDrainer:
        break;
    case Level_Name_BlackBloodStar:
        break;
    case Level_Name_Planets:
        break;
    case Level_Name_OuterGodsAngels:
        break;
    case Level_Name_OuterGod:
        break;
    case Level_Name_MAX:
        break;
    }
}


Ability_Name worshipper_unlocks[] = {
    Ability_Name_DEBUG_DAMAGE, Ability_Name_DEBUG_HEAL,
};


Level_Unlock_Rewards get_level_unlock_rewards_data(Level_Name level_name)
{
    switch (level_name)
    {
    case Level_Name_None:
        break;
    case Level_Name_Sandbox:
        break;
    case Level_Name_Tutorial:
        break;
    case Level_Name_Worshipper:
        return (Level_Unlock_Rewards){ARRAY_SIZE(worshipper_unlocks), worshipper_unlocks};
        break;
    case Level_Name_BurningSoul:
        break;
    case Level_Name_IceQueen:
        break;
    case Level_Name_SunMoonTwin:
        break;
    case Level_Name_BrotherInArms:
        break;
    case Level_Name_BloodBrothers:
        break;
    case Level_Name_HealSquad:
        break;
    case Level_Name_Freezer:
        break;
    case Level_Name_MetalStar:
        break;
    case Level_Name_Abyssal:
        break;
    case Level_Name_Slimes:
        break;
    case Level_Name_CountDown:
        break;
    case Level_Name_ReversalReversal:
        break;
    case Level_Name_Angel:
        break;
    case Level_Name_Demon:
        break;
    case Level_Name_FusionMania:
        break;
    case Level_Name_Persona:
        break;
    case Level_Name_DisfiguredMass:
        break;
    case Level_Name_InsanityProgenitor:
        break;
    case Level_Name_Dancer:
        break;
    case Level_Name_Player:
        break;
    case Level_Name_Law:
        break;
    case Level_Name_Shield:
        break;
    case Level_Name_Time1:
        break;
    case Level_Name_Time2:
        break;
    case Level_Name_Time3:
        break;
    case Level_Name_Time4:
        break;
    case Level_Name_Time5:
        break;
    case Level_Name_Tribe:
        break;
    case Level_Name_Conjure:
        break;
    case Level_Name_3SisterFather:
        break;
    case Level_Name_MultiElemental:
        break;
    case Level_Name_MPDrainer:
        break;
    case Level_Name_BlackBloodStar:
        break;
    case Level_Name_Planets:
        break;
    case Level_Name_OuterGodsAngels:
        break;
    case Level_Name_OuterGod:
        break;
    case Level_Name_MAX:
        break;
    }

    MASSERT(false);
    return (Level_Unlock_Rewards){0};
}

void unlock_next_level(Save_Game* save_game)
{
}


#endif //MISSION_H
